### ISSUE TITLE
Holistic-Web Website

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/project-tracker#5]
Replace the existing holding page (hopefully port the logic to keep the physcis effect) with a page showcasing our work to show to clients.

Features we might like:
- view projects by type / features
- contact us / request work
- internal messaging / project managing?
- use github as a content delivery system (show what we're working on through github)

**Comment by Charlielancaster** [comment]
I like this, have Holistics as the holding page with all of our personal profiles as other pages (Useful for clients so they can meet the team blah blah blah)

**Comment by michaelfitzhavey** [comment]
This exists now 🎈
